// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKyEn388XtoUHPnI9Zm4srO_SeCw5ij5U',
    appId: '1:683124011929:web:f2151a4b1f2aac421c9908',
    messagingSenderId: '683124011929',
    projectId: 'mykamus-personal',
    authDomain: 'mykamus-personal.firebaseapp.com',
    databaseURL: 'https://mykamus-personal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mykamus-personal.firebasestorage.app',
    measurementId: 'G-DDNWPB2BF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXrDEyEmqDMbyRTz7lypFtbg3vl1UywbU',
    appId: '1:683124011929:android:055774cace57de7b1c9908',
    messagingSenderId: '683124011929',
    projectId: 'mykamus-personal',
    databaseURL: 'https://mykamus-personal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mykamus-personal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk1g_nJknnOmFEzLDE12bR6LrLrkcMi4U',
    appId: '1:683124011929:ios:09c12bb0de1141ae1c9908',
    messagingSenderId: '683124011929',
    projectId: 'mykamus-personal',
    databaseURL: 'https://mykamus-personal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mykamus-personal.firebasestorage.app',
    iosBundleId: 'com.example.myKamusPersonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk1g_nJknnOmFEzLDE12bR6LrLrkcMi4U',
    appId: '1:683124011929:ios:09c12bb0de1141ae1c9908',
    messagingSenderId: '683124011929',
    projectId: 'mykamus-personal',
    databaseURL: 'https://mykamus-personal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mykamus-personal.firebasestorage.app',
    iosBundleId: 'com.example.myKamusPersonal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKyEn388XtoUHPnI9Zm4srO_SeCw5ij5U',
    appId: '1:683124011929:web:07572be289c53de51c9908',
    messagingSenderId: '683124011929',
    projectId: 'mykamus-personal',
    authDomain: 'mykamus-personal.firebaseapp.com',
    databaseURL: 'https://mykamus-personal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mykamus-personal.firebasestorage.app',
    measurementId: 'G-EHJTZ8VFBW',
  );
}
